### ISSUE TITLE
gym.make('ppaquette/DoomBasic-v0') fails

### ISSUE THREAD

**Issue by sahiliitm** [ppaquette/gym-doom#1]
Hi,

When I execute the code specified on the repo's github page, I get the following error:

```
>>> env = gym.make('ppaquette/DoomBasic-v0')
[2016-10-06 02:15:18,376] Making new env: ppaquette/DoomBasic-v0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 126, in make
    return registry.make(id)
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 90, in make
    spec = self.spec(id)
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 112, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: ppaquette/DoomBasic-v0
```

Any idea what this error could be?
Thanks!

**Comment by ppaquette** [comment]
You need to install the envs first.

First, you need to install gym-pull

```
    pip install gym-pull
```

Then, to load and run the environments, run

```
    import gym
    import gym_pull
    gym_pull.pull('github.com/ppaquette/gym-doom')        # Only required once, envs will be loaded with import gym_pull afterwards
    env = gym.make('ppaquette/DoomBasic-v0')
```
