### ISSUE TITLE
Cannot upload evaluation to https://gym.openai.com/envs/DoomBasic-v0

### ISSUE THREAD

**Issue by pilipolio** [ppaquette/gym-doom#10]
Is there a way to visualise my evaluation on https://gym.openai.com?

Thanks!

```
2017-02-19 18:42:46,171] [ppaquette/DoomBasic-v0] Creating evaluation object from /tmp/random-agent-results with learning curve and training video
Traceback (most recent call last):
  File "gym/examples/agents/random_agent.py", line 68, in <module>
    gym.upload(outdir)
  File "/Users/gui/.virtualenvs/gui3/lib/python3.6/site-packages/gym/scoreboard/api.py", line 83, in upload
    evaluation = _upload(training_dir, algorithm_id, writeup, benchmark_run_id, api_key, ignore_open_monitors)
  File "/Users/gui/.virtualenvs/gui3/lib/python3.6/site-packages/gym/scoreboard/api.py", line 132, in _upload
    api_key=api_key,
  File "/Users/gui/.virtualenvs/gui3/lib/python3.6/site-packages/gym/scoreboard/client/resource.py", line 323, in create
    response, api_key = requestor.request('post', url, params, headers)
  File "/Users/gui/.virtualenvs/gui3/lib/python3.6/site-packages/gym/scoreboard/client/api_requestor.py", line 41, in request
    resp = self.interpret_response(rbody, rcode, rheaders)
  File "/Users/gui/.virtualenvs/gui3/lib/python3.6/site-packages/gym/scoreboard/client/api_requestor.py", line 157, in interpret_response
    self.handle_api_error(rbody, rcode, resp, rheaders)
  File "/Users/gui/.virtualenvs/gui3/lib/python3.6/site-packages/gym/scoreboard/client/api_requestor.py", line 55, in handle_api_error
    rbody, rcode, resp, rheaders)
gym.error.InvalidRequestError: Request req_XXXX: This version of the environment is not registered on the server, but other versions exist. You may need to upgrade your version of gym. Env ppaquette/DoomBasic-v0 not found (valid versions include ['DoomBasic-v0'])```

**Comment by pilipolio** [comment]
Hmmm, I have found a work-around doing

```
env_spec = gym.spec('ppaquette/DoomBasic-v0')
env_spec.id = 'DoomBasic-v0'
env = env_spec.make()
```

I am then able to upload it to the score board
