### ISSUE TITLE
Consistent error in installing ppaquette-gym-doom

### ISSUE THREAD

**Issue by shubhoghosal** [ppaquette/gym-doom#20]
Hello Philip,
I tried installing this package on both MacOS (High Sierra) and Windows 7, with both Python 2.7 and 3.6 (Anaconda in both environments, also tried WinPython on Win7). I am consistently getting the same error with the install of doom_py. Error below.
Tried both a direct pip install and gym-pull. Gym-pull is itself giving an issue with Python 2.7.
Is there anything you can suggest as an alternative or to troubleshoot? I am doing this for an AI course and this has me completely stalled.
Sorry for the bother and thanks!
SG
    Could not build doom-py: Command '['make', '-j', '7']' returned non-zero exit status 2. (HINT: are you sure cmake is installed? You might also be missing a library. doom_py requires boost, boost-python, sdl2 on OSX (installable via 'brew install boost boost-python sdl2')
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/01/sk2yzmcd4cxby3nxt6z1c3jw0000gn/T/pip-build-B50BNA/doom-py/setup.py", line 88, in <module>
        include_package_data=True,
      File "/Users/shubhoghosal/anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/Users/shubhoghosal/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/Users/shubhoghosal/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Users/shubhoghosal/anaconda2/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Users/shubhoghosal/anaconda2/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/Users/shubhoghosal/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/Users/shubhoghosal/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/var/folders/01/sk2yzmcd4cxby3nxt6z1c3jw0000gn/T/pip-build-B50BNA/doom-py/setup.py", line 63, in run
        build_func()
      File "/private/var/folders/01/sk2yzmcd4cxby3nxt6z1c3jw0000gn/T/pip-build-B50BNA/doom-py/setup.py", line 34, in build_osx
        build_common('dylib', cmake_arg_list=['-DOSX_COCOA_BACKEND=OFF'])
      File "/private/var/folders/01/sk2yzmcd4cxby3nxt6z1c3jw0000gn/T/pip-build-B50BNA/doom-py/setup.py", line 29, in build_common
        subprocess.check_call(['make', '-j', str(cores_to_use)], cwd='doom_py')
      File "/Users/shubhoghosal/anaconda2/lib/python2.7/subprocess.py", line 186, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', '-j', '7']' returned non-zero exit status 2
    
    ----------------------------------------
Command "/Users/shubhoghosal/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/01/sk2yzmcd4cxby3nxt6z1c3jw0000gn/T/pip-build-B50BNA/doom-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/01/sk2yzmcd4cxby3nxt6z1c3jw0000gn/T/pip-kDAVls-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/01/sk2yzmcd4cxby3nxt6z1c3jw0000gn/T/pip-build-B50BNA/doom-py/

**Comment by shubhoghosal** [comment]
Would like to add that the prereqs in the HINT section are already installed
