### ISSUE TITLE
gym (0.9.3), like in super mario ImportError: No module named 'gym.scoreboard.registration'

### ISSUE THREAD

**Issue by dialogchat** [ppaquette/gym-doom#23]
```
import gym
import ppaquette_gym_doom
env = gym.make('ppaquette/DoomBasic-v0')

```

Traceback (most recent call last):
  File "super_mario_1.py", line 7, in <module>
    import ppaquette_gym_doom
  File "/usr/local/lib/python3.5/dist-packages/ppaquette_gym_doom/__init__.py", line 2, in <module>
    from gym.scoreboard.registration import add_task, add_group
ImportError: No module named 'gym.scoreboard.registration'

**Comment by ChiragAnilkumar** [comment]
I have raised this issue in gym repo, they said the website for scoreboard was deprecated and hence the file was removed as the backened did not exist. I have opened this issue here to use an older version of gym or some workarounds.
However for the moment as non elegant workaround you can download the code from internet, just google
