### ISSUE TITLE
Missing module gym.scoreboard.registration.py

### ISSUE THREAD

**Issue by ChiragAnilkumar** [ppaquette/gym-doom#25]
In gym-doom/ppaquette_gym_doom/__init__.py there is a line of code which imports add_group and add_task  from gym.scoreboard.registration. I had raised this issue in openai/gym repo, they said the website for scoreboard was deprecated and hence the file was removed as there was no backend. So please provide instructions to use an older version of gym or update the code to make some change.

**Comment by cuznerdexter** [comment]
Getting this error when trying to import into my anaconda environment.
This is the error displayed in Spyder

```
import ppaquette_gym_doom

Traceback (most recent call last):
  File "<ipython-input-6-18277e8ec3c6>", line 1, in 
<module>
    import ppaquette_gym_doom
  File "/Users/cuznerdexter/anaconda/envs/doom_ai_py36_cpu/lib/python3.6/site-packages/ppaquette_gym_doom/__init__.py", line 2, in 
<module>
    
from gym.scoreboard.registration import add_task, add_group

ModuleNotFoundError: No module named 'gym.scoreboard.registration'
```

**Comment by hatoshi11** [comment]
Having the same issue, whats the workaround?

**Comment by ChiragAnilkumar** [comment]
Presently either use an older version of openai/gym repo or just download the code for gym.scoreboard.registration.py from internet.

**Comment by cuznerdexter** [comment]
@ChiragAnilkumar great thanks. Will give that a try.

**Comment by dnyaneshwar89** [comment]
> Presently either use an older version of openai/gym repo or just download the code for gym.scoreboard.registration.py from internet.

can you provide link to find registration.py ?
