### ISSUE TITLE
Installation via pip fails at Boost

### ISSUE THREAD

**Issue by firu** [ppaquette/gym-doom#30]
Hello,

I am trying to install gym-doom on my Ubuntu 18.10 with Python 3.6.8 via:

> pip3 install ppaquette-gym-doom

All dependencies are fulfilled:

> sudo apt-get install -y python-numpy cmake zlib1g-dev libjpeg-dev libboost-all-dev gcc libsdl2-dev wget unzip git
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> cmake is already the newest version (3.12.1-1).
> libjpeg-dev is already the newest version (8c-2ubuntu8).
> python-numpy is already the newest version (1:1.14.5-1ubuntu4).
> unzip is already the newest version (6.0-21ubuntu1).
> zlib1g-dev is already the newest version (1:1.2.11.dfsg-0ubuntu2).
> libboost-all-dev is already the newest version (1.67.0.0ubuntu1).
> libsdl2-dev is already the newest version (2.0.8+dfsg1-4ubuntu1).
> gcc is already the newest version (4:8.3.0-1ubuntu1.2).
> git is already the newest version (1:2.19.1-1ubuntu1.1).
> wget is already the newest version (1.19.5-1ubuntu1.1).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Apparently, it fails at doom-py part with:

>   -- Could NOT find Boost
>   -- Boost library python-py3:
>   -- Could NOT find Boost
>   -- Boost library python3:
>   CMake Error at /usr/share/cmake-3.12/Modules/FindBoost.cmake:2063 (message):
>     Unable to find the requested Boost libraries.
>   
>     Boost version: 1.67.0
>   
>     Boost include path: /usr/include
>   
>     Could not find the following Boost libraries:
>   
>             boost_python
>   
>     No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
>     directory containing Boost libraries or BOOST_ROOT to the location of
>     Boost.
>   Call Stack (most recent call first):
>   CMakeLists.txt:151 (find_package)
>  [...]
>  ----------------------------------------
>  Failed building wheel for doom-py

I have tried to set BOOST_LIBRARYDIR  and BOOST_ROOT to /usr/include/boost, does not work.
Apparently, there are libboost-python files in:

> /usr/lib/x86_64-linux-gnu/libboost_python
> libboost_python27.a          libboost_python36.so.1.67.0  libboost_python3-py36.a
> libboost_python27.so         libboost_python37.a          libboost_python3-py36.so
> libboost_python27.so.1.67.0  libboost_python37.so         libboost_python3.so
> libboost_python36.a          libboost_python37.so.1.67.0  libboost_python.a
> libboost_python36.so         libboost_python3.a           libboost_python.so

I deeply appreciate any help!
Thank you and kind regards,
*firu

**Comment by firu** [comment]
Well, following  [https://github.com/hardmaru/WorldModelsExperiments/issues/12] got me one step further.
Now, when using doom-py, I've got:

> RuntimeError: FATAL: module compiled as little endian, but detected different endianness at runtime
> Traceback (most recent call last):
>   File "extract.py", line 11, in <module>
>     from doomreal import _process_frame
>   File "/home/firu/WorldModelsExperiments/doomrnn/doomreal.py", line 6, in <module>
>     import doom_py
>   File "/home/firu/.local/lib/python3.6/site-packages/doom_py/__init__.py", line 1, in <module>
>     from doom_py.vizdoom import *

Now, there is a problem with the detection, as I am indeed using a x86_64 machine, which is a little endian.

**Comment by DanielTakeshi** [comment]
I don't think this repository is maintained anymore.
