### ISSUE TITLE
Error when installing the environment through gym_pull

### ISSUE THREAD

**Issue by bnurbekov** [ppaquette/gym-doom#7]
I am encountering the following error when executing `gym_pull.pull('github.com/ppaquette/gym-doom')`:
```
Building wheels for collected packages: doom-py
  Running setup.py bdist_wheel for doom-py ... error
  Complete output from command c:\python35_64\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\batyr\\AppData\\Local\\Temp\\pip-build-90y4rngd\\doom-py\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\batyr\AppData\Local\Temp\tmpi7gnio4jpip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\batyr\AppData\Local\Temp\pip-build-90y4rngd\doom-py\setup.py", line 88, in <module>
      include_package_data=True,
    File "c:\python35_64\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\python35_64\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "c:\python35_64\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\python35_64\lib\site-packages\wheel\bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "c:\python35_64\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\python35_64\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\batyr\AppData\Local\Temp\pip-build-90y4rngd\doom-py\setup.py", line 63, in run
      build_func()
    File "C:\Users\batyr\AppData\Local\Temp\pip-build-90y4rngd\doom-py\setup.py", line 45, in build_windows
      build_common('dll')
    File "C:\Users\batyr\AppData\Local\Temp\pip-build-90y4rngd\doom-py\setup.py", line 23, in build_common
      python_library = find_python_library()
    File "C:\Users\batyr\AppData\Local\Temp\pip-build-90y4rngd\doom-py\setup.py", line 16, in find_python_library
      python_library = os.path.join(sysconfig.get_config_var(var), 'libpython{}.{}'.format(sysconfig.get_python_version(), dynamic_library_extension))
    File "c:\python35_64\lib\ntpath.py", line 113, in join
      genericpath._check_arg_types('join', path, *paths)
    File "c:\python35_64\lib\genericpath.py", line 143, in _check_arg_types
      (funcname, s.__class__.__name__)) from None
  TypeError: join() argument must be str or bytes, not 'NoneType'

  ----------------------------------------
  Failed building wheel for doom-py
```
Any ideas on how to resolve it?

I am executing this command on a 64-bit Windows 10 machine with Python 3.5.2.

**Comment by 222464** [comment]
Hello,

I am also interested in this. I have the same error, also Windows 10 64 bit with Python 3.5.2. I used the second install method, it seems to produce this error as well.

**Comment by ppaquette** [comment]
Unfortunately, the doom_py package doesn't support Windows.

**Comment by shubhoghosal** [comment]
same error on macos
