### ISSUE TITLE
Unregistered environment, even though gym pull was correctly installed and used

### ISSUE THREAD

**Issue by mishra-arjun** [ppaquette/gym-doom#8]
Hi

I am getting the unregistered environment error as was raised by someone a while back:
Traceback (most recent call last):

  File "/home/arjun/anaconda3/lib/python3.5/site-packages/gym/envs/registration.py", line 116, in spec
    return self.env_specs[id]
KeyError: 'ppaquette/DoomBasic-v0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/arjun/anaconda3/lib/python3.5/site-packages/gym/envs/registration.py", line 140, in make
    return registry.make(id)
  File "/home/arjun/anaconda3/lib/python3.5/site-packages/gym/envs/registration.py", line 104, in make
    spec = self.spec(id)
  File "/home/arjun/anaconda3/lib/python3.5/site-packages/gym/envs/registration.py", line 126, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: ppaquette/DoomBasic-v0

I have tried all the alternatives suggested: installed all the dependencies on python 3.5 and 2.7. I also tried making the environment using the second option and I get the following error, even though I have doom_py installed:

Traceback (most recent call last):
  File "/home/arjun/anaconda3/lib/python3.5/site-packages/ppaquette_gym_doom/doom_env.py", line 13, in <module>
    import doom_py
  File "/home/arjun/anaconda3/lib/python3.5/site-packages/doom_py/__init__.py", line 1, in <module>
    from doom_py.vizdoom import *
ImportError: /home/arjun/anaconda3/lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/arjun/anaconda3/lib/python3.5/site-packages/doom_py/vizdoom.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/arjun/anaconda3/lib/python3.5/site-packages/ppaquette_gym_doom/__init__.py", line 4, in <module>
    from .doom_env import DoomEnv, MetaDoomEnv
  File "/home/arjun/anaconda3/lib/python3.5/site-packages/ppaquette_gym_doom/doom_env.py", line 18, in <module>
    "with 'pip install doom_py.)'".format(e))
gym.error.DependencyNotInstalled: {}. (HINT: you can install Doom dependencies with 'pip install doom_py.)'

Any help at all would be highly appreciated.

**Comment by mishra-arjun** [comment]
Solved the problem by downloading the github repo and running setup from there.

**Comment by dookdick** [comment]
Hi mishra

Seems like I have the similar problem;

 File "<ipython-input-1-f5bb3b463366>", line 11, in <module>
    from ppaquette_gym_doom.wrappers.action_space import ToDiscrete

  File "/home/nat/anaconda3/lib/python3.6/site-packages/ppaquette_gym_doom/__init__.py", line 4, in <module>
    from .doom_env import DoomEnv, MetaDoomEnv

  File "/home/nat/anaconda3/lib/python3.6/site-packages/ppaquette_gym_doom/doom_env.py", line 18, in <module>
    "with 'pip install doom_py.)'".format(e))

DependencyNotInstalled: {}. (HINT: you can install Doom dependencies with 'pip install doom_py.)'

Could you please advise which repo I might need to download and run?

Truly appreciate your help in advance
Nat

**Comment by mishra-arjun** [comment]
Hi

You can download the gym-doom repository directly from ppaquette's github page. Once you have, you can run setup.py (contained in the gym-doom repository itself) in shell and that should install the package in python.

**Comment by dookdick** [comment]
Hi Mishra

I've finally managed to download the gym_doom repo, and successfully installed. However, I still got the same error I had before.   
..................................................................................................................................................................
Traceback (most recent call last):

  File "<ipython-input-1-f9b257646825>", line 11, in <module>
    from ppaquette_gym_doom.wrappers.action_space import ToDiscrete

  File "/home/nat/anaconda3/lib/python3.6/site-packages/ppaquette_gym_doom/__init__.py", line 4, in <module>
    from .doom_env import DoomEnv, MetaDoomEnv

  File "/home/nat/anaconda3/lib/python3.6/site-packages/ppaquette_gym_doom/doom_env.py", line 18, in <module>
    "with 'pip install doom_py.)'".format(e))

DependencyNotInstalled: {}. (HINT: you can install Doom dependencies with 'pip install doom_py.)'
.....................................................................................................................................................................
I've also successfully installed the following as mentioned in ppaquette/gym-doom github;
 
pip install gym-pull
pip install ppaquette-gym-doom

Anyway, I received another error when trying to run the DoomCorridor-v0 env though. 
................................................................................................................................................................
import gym
import ppaquette_gym_doom
env = gym.make('ppaquette/DoomCorridor-v0')

Traceback (most recent call last):

  File "<ipython-input-5-8635b5a5f2df>", line 2, in <module>
    import ppaquette_gym_doom

  File "/home/nat/anaconda3/lib/python3.6/site-packages/ppaquette_gym_doom/__init__.py", line 4, in <module>
    from .doom_env import DoomEnv, MetaDoomEnv

  File "/home/nat/anaconda3/lib/python3.6/site-packages/ppaquette_gym_doom/doom_env.py", line 18, in <module>
    "with 'pip install doom_py.)'".format(e))

DependencyNotInstalled: {}. (HINT: you can install Doom dependencies with 'pip install doom_py.)'
..............................................................................................................................................................
import gym
import gym_pull
gym_pull.pull('github.com/ppaquette/gym-doom')        
env = gym.make('ppaquette/DoomCorridor-v0')

Traceback (most recent call last):

  File "<ipython-input-6-837fb78e33d0>", line 2, in <module>
    import gym_pull

  File "/home/nat/anaconda3/lib/python3.6/site-packages/gym_pull/__init__.py", line 43, in <module>
    gym.upload = gym_pull.scoreboard.api.upload

AttributeError: module 'gym_pull' has no attribute 'scoreboard'
................................................................................................................................................................

So, what else should I do to make my AI experiment on DoomCorridoor-v0 run.

Thanks in advance
Nat
